# Generated by Django 5.2.9 on 2025-12-10 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        default="ACTIVA",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("periodo_academico", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo_entrega", models.CharField(max_length=255)),
                ("comentarios_estudiante", models.TextField(blank=True)),
                ("fecha_entrega", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_entrega",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENTREGADO", "Entregado"),
                        ],
                        default="ENTREGADO",
                        max_length=15,
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("retroalimentacion_docente", models.TextField(blank=True)),
                ("fecha_calificacion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado_calificacion",
                    models.CharField(
                        choices=[
                            ("SIN_CALIFICAR", "Sin calificar"),
                            ("CALIFICADO", "Calificado"),
                        ],
                        default="SIN_CALIFICAR",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordatorioTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_recordatorio",
                    models.CharField(
                        choices=[
                            ("3_DIAS", "Tres días antes"),
                            ("1_DIA", "Un día antes"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha_programada", models.DateTimeField()),
                ("enviado", models.BooleanField(default=False)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReporteMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=20)),
                ("datos", models.JSONField()),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField()),
                (
                    "fecha_publicacion",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("fecha_vencimiento", models.DateField()),
                (
                    "peso_porcentual",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "tipo_tarea",
                    models.CharField(
                        choices=[("TAREA", "Tarea"), ("EXAMEN", "Examen")],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        default="ACTIVA",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_publicacion"],
            },
        ),
    ]
