# Generated by Django 5.2.9 on 2025-12-10 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Academico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="docente_responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asignaturas_dirigidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="estudiantes",
            field=models.ManyToManyField(
                blank=True,
                related_name="asignaturas_inscritas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tarea",
            name="asignatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tareas",
                to="Academico.asignatura",
            ),
        ),
        migrations.AddField(
            model_name="recordatoriotarea",
            name="tarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios",
                to="Academico.tarea",
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="tarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="Academico.tarea",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recordatoriotarea",
            unique_together={("tarea", "tipo_recordatorio")},
        ),
        migrations.AlterUniqueTogether(
            name="entrega",
            unique_together={("tarea", "estudiante")},
        ),
    ]
